apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ikcz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ikcz
    app.kubernetes.io/part-of: tkrw-pr714-0075-0052-app
  name: devfile-sample-ikcz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ikcz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ikcz
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0052-tenant/tkrw-pr714-0075-0052-app/devfile-sample-ikcz@sha256:cfcedc480206b6646711d0533045d787909a9a1d62be273d6fa1fb7b758c3252
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
